from typing import Protocol
from uuid import UUID

from core.model.llm_credential import LLMCredential


class LLMCredentialStore(Protocol):
    def get(self, user_id: UUID, provider: str) -> LLMCredential | None: ...
    def upsert(
        self, user_id: UUID, provider: str, encrypted_key: bytes, last4: str
    ) -> LLMCredential: ...
    def delete(self, user_id: UUID, provider: str) -> bool: ...
    def list_for_user(self, user_id: UUID) -> list[LLMCredential]: ...
    def update_test_result(
        self, user_id: UUID, provider: str, ok: bool, error: str | None
    ) -> None: ...
    def get_encrypted_key(self, user_id: UUID, provider: str) -> bytes | None: ...
