from typing import Protocol
from uuid import UUID

from core.model.user import SubscriptionPlan, User, UserLimits, UserSubscription


class UserStore(Protocol):
    def get_by_id(self, user_id: UUID) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def create(self, email: str, password_hash: str, display_name: str | None) -> User: ...
    def update(self, user: User) -> User: ...
    def get_document_count(self, user_id: UUID) -> int: ...
    def get_tree_count(self, user_id: UUID) -> int: ...


class SubscriptionPlanStore(Protocol):
    def get_by_slug(self, slug: str) -> SubscriptionPlan | None: ...
    def get_by_id(self, plan_id: UUID) -> SubscriptionPlan | None: ...
    def list_active(self) -> list[SubscriptionPlan]: ...


class UserSubscriptionStore(Protocol):
    def get_for_user(self, user_id: UUID) -> UserSubscription | None: ...
    def get_plan_for_user(self, user_id: UUID) -> SubscriptionPlan | None: ...
    def assign_plan(self, user_id: UUID, plan_slug: str) -> UserSubscription: ...
    def get_user_limits(self, user_id: UUID) -> UserLimits: ...
